/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BUS.ChitietphieunhapBUS;
import static java.lang.Integer.parseInt;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import BUS.PhieunhapBUS;
import BUS.SanphamBUS;
import DTO.ChitietphieunhapDTO;
import DTO.PhieunhapDTO;
import DTO.SanPhamDTO;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ThemPNGUI extends javax.swing.JFrame {

    /**
     * Creates new form PhieuNhap_Add
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */

    public ThemPNGUI() throws Exception {
        initComponents();
        
        PhieunhapBUS bus = new PhieunhapBUS();
        
        String KeyString = bus.taoMaPN();
        
        Date date = (Date) Calendar.getInstance().getTime();
        DateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy hh:mm:ss");  
        String strDate = dateFormat.format(date);
        
        txt_MaPN.setText(KeyString);
        txt_Ngaynhap.setText(strDate);
        txt_Tongtien.setText("0");
        txt_MaNV.requestFocus();
        
        Vector header = new Vector();
        header.add("Mã Sản Phẩm");
        header.add("Tên Sản Phẩm");
        header.add("Số Lượng");
        header.add("Đơn Giá");

        model = new DefaultTableModel(header,0);
        
        tbl_DSSP.setModel(model);
    }

    public void setTxt_MaSP(String txt) {
        txt_MaSP.setText(txt);
    }

    public void setTxt_MaNCC(String txt) {
        txt_MaNCC.setText(txt);
    }

    public void setTxt_MaNV(String txt) {
        txt_MaNV.setText(txt);
    }
    
    
       
    ArrayList<ChitietphieunhapDTO> dsct = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_MaPN = new javax.swing.JTextField();
        txt_Ngaynhap = new javax.swing.JTextField();
        txt_Tongtien = new javax.swing.JTextField();
        txt_MaNV = new javax.swing.JTextField();
        txt_MaNCC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSearchNV = new javax.swing.JButton();
        btnSearchNCC = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnTrolai = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_DSSP = new javax.swing.JTable();
        btnConfirm = new javax.swing.JButton();
        txt_MaSP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnFindSP = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        sp_SoLuong = new javax.swing.JSpinner();
        btnXoaCT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txt_MaPN.setEditable(false);
        txt_MaPN.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_Ngaynhap.setEditable(false);
        txt_Ngaynhap.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_Tongtien.setEditable(false);
        txt_Tongtien.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txt_MaNV.setEditable(false);
        txt_MaNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_MaNV.setText("Chọn Mã Nhân Viên");
        txt_MaNV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MaNVKeyPressed(evt);
            }
        });

        txt_MaNCC.setEditable(false);
        txt_MaNCC.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_MaNCC.setText("Chọn Mã Nhà Cung Cấp");
        txt_MaNCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MaNCCKeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("000 Blambot Casual [TeddyBear]", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Phiếu Nhập");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ImageIcon icon = new ImageIcon("src\\img\\icon\\icon thêm.png");
        jLabel1.setIcon(icon);
        btnThem.setIcon(icon);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Mã Phiếu Nhập :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Nhà Cung Cấp :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Ngày Nhập :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Tổng Tiền :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Nhân Viên :");

        btnSearchNV.setText("...");
        btnSearchNV.setFocusPainted(false);
        btnSearchNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNVActionPerformed(evt);
            }
        });

        btnSearchNCC.setText("...");
        btnSearchNCC.setFocusPainted(false);
        btnSearchNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchNCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Ngaynhap, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_MaPN)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_MaNV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchNV))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txt_MaNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearchNCC))
                            .addComponent(txt_Tongtien))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaPN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Ngaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchNV))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_MaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchNCC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_Tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        btnThem.setBackground(new java.awt.Color(204, 255, 153));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnTrolai.setText("Trở Lại");
        btnTrolai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrolaiActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tbl_DSSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_DSSP);

        btnConfirm.setText("Xác nhận");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        txt_MaSP.setEditable(false);
        txt_MaSP.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txt_MaSP.setText("Chọn Mã Sản Phẩm");
        txt_MaSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MaSPKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Mã Sản Phẩm:");

        jLabel6.setFont(new java.awt.Font("000 Blambot Casual [TeddyBear]", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Chi tiết");

        btnFindSP.setText("...");
        btnFindSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindSPActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Số Lượng:");

        sp_SoLuong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sp_SoLuong.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        sp_SoLuong.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        sp_SoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sp_SoLuongKeyPressed(evt);
            }
        });

        btnXoaCT.setText("Xóa");
        btnXoaCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnXoaCT)
                        .addGap(18, 18, 18)
                        .addComponent(btnConfirm))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(txt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFindSP))
                            .addComponent(sp_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindSP))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sp_SoLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnXoaCT))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addGap(322, 322, 322)
                        .addComponent(btnTrolai, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTrolai, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        PhieunhapBUS bus = new PhieunhapBUS();
        PhieunhapDTO pn = new PhieunhapDTO();
                       
        {            
            pn.setMaPN(txt_MaPN.getText());
            pn.setTongTien(parseInt(txt_Tongtien.getText()));
            pn.setMaNCC(txt_MaNCC.getText());
            pn.setMaNV(txt_MaNV.getText());

            txt_Tongtien.setText("0");
            txt_MaNV.setText("Chọn Mã Nhân Viên");
            txt_MaNCC.setText("Chọn Mã Nhà Cung Cấp");
                   
            try {
                bus.them(pn);
            } catch (Exception ex) {
                Logger.getLogger(ThemPNGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            String KeyString = "";

            try {
                KeyString = bus.taoMaPN();
            } catch (Exception ex) {
                Logger.getLogger(ThemPNGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            txt_MaPN.setText(KeyString);
            txt_MaSP.setText("Chọn Mã Sản Phẩm");
            sp_SoLuong.setValue(0); 
        }
        
        ChitietphieunhapBUS chitietBUS = new ChitietphieunhapBUS();
        for(ChitietphieunhapDTO ctpn : dsct){
            try {
                chitietBUS.them(ctpn);
            } catch (Exception ex) {
                Logger.getLogger(ThemPNGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnTrolaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrolaiActionPerformed
        try {
            new PhieuNhapGUI().setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ThemPNGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();                
    }//GEN-LAST:event_btnTrolaiActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed

        ChitietphieunhapDTO chitiet = new ChitietphieunhapDTO();
        SanphamBUS spBUS = new SanphamBUS();
        
            chitiet.setMaPN(txt_MaPN.getText());
            chitiet.setMaSP(txt_MaSP.getText());
            
        try {
            sp_SoLuong.commitEdit();
        } catch (ParseException ex) {
            Logger.getLogger(ThemPNGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
            chitiet.setSoLuong((Integer)sp_SoLuong.getValue());
            
                model = (DefaultTableModel) tbl_DSSP.getModel();
                SanPhamDTO sp = new SanPhamDTO();
                try {
                    sp = spBUS.timkiemSPTheoMaSP(chitiet.getMaSP());
                } catch (Exception ex) {
                    Logger.getLogger(ThemPNGUI.class.getName()).log(Level.SEVERE, null, ex);
                }

                    Vector row = new Vector();
                    row.add(sp.getMaSP());
                    row.add(sp.getTenSP());
                    row.add(chitiet.getSoLuong());
                    row.add(sp.getDonGia());
                    model.addRow(row);

                tbl_DSSP.setModel(model);

                chitiet.setDonGia((int) sp.getDonGia());
                chitiet.setThanhTien(chitiet.getDonGia()*chitiet.getSoLuong());
                dsct.add(chitiet);
                
                int TongTien = parseInt(txt_Tongtien.getText());
                TongTien += chitiet.getThanhTien();
                txt_Tongtien.setText(""+TongTien);                              
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnXoaCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCTActionPerformed
        model = (DefaultTableModel) tbl_DSSP.getModel();
        
        int vitri = tbl_DSSP.getSelectedRow();

        if(vitri == -1) 
           JOptionPane.showMessageDialog(null, "Chưa chọn dòng cần xóa!");
        else{
            if(JOptionPane.showConfirmDialog(null,"Bạn muốn bỏ sản phẩm này khỏi danh sách?","Xác nhận xóa",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){       
            model.removeRow(vitri);
            ChitietphieunhapDTO ctpn = dsct.get(vitri);
            int Tong = parseInt(txt_Tongtien.getText()) - ctpn.getThanhTien();
            txt_Tongtien.setText("" + Tong);
            dsct.remove(vitri);

            tbl_DSSP.setModel(model);
            }
        }
    }//GEN-LAST:event_btnXoaCTActionPerformed

    private void txt_MaNVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MaNVKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txt_MaNCC.requestFocus();
        }
    }//GEN-LAST:event_txt_MaNVKeyPressed

    private void txt_MaNCCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MaNCCKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            txt_MaSP.requestFocus();
        }
        else 
            if(evt.getKeyCode() == KeyEvent.VK_UP){
                txt_MaNV.requestFocus();
            }
    }//GEN-LAST:event_txt_MaNCCKeyPressed

    private void txt_MaSPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MaSPKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            sp_SoLuong.requestFocus();
        }
        else 
            if(evt.getKeyCode() == KeyEvent.VK_UP){
                txt_MaNCC.requestFocus();
            }        
    }//GEN-LAST:event_txt_MaSPKeyPressed

    private void sp_SoLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sp_SoLuongKeyPressed
            if(evt.getKeyCode() == KeyEvent.VK_UP){
                txt_MaSP.requestFocus();
            }         
    }//GEN-LAST:event_sp_SoLuongKeyPressed

    private void btnFindSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindSPActionPerformed
        try {
            new AdvancedSearchGUI(this).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ThemPNGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFindSPActionPerformed

    private void btnSearchNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNVActionPerformed
        new SearchNVNCGUI(this).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchNVActionPerformed

    private void btnSearchNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchNCCActionPerformed
        try {
            new SearchNCC(this).setVisible(true);        // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(ThemPNGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchNCCActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPNGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPNGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPNGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPNGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and dipnlay the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ThemPNGUI().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ThemPNGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnFindSP;
    private javax.swing.JButton btnSearchNCC;
    private javax.swing.JButton btnSearchNV;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTrolai;
    private javax.swing.JButton btnXoaCT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner sp_SoLuong;
    private javax.swing.JTable tbl_DSSP;
    public javax.swing.JTextField txt_MaNCC;
    public javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_MaPN;
    public javax.swing.JTextField txt_MaSP;
    private javax.swing.JTextField txt_Ngaynhap;
    private javax.swing.JTextField txt_Tongtien;
    // End of variables declaration//GEN-END:variables
}
