/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.KeyEvent;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import BUS.SanphamBUS;
import BUS.TaikhoanBUS;
import BUS.initDefaultBUS;
import DTO.SanPhamDTO;
import DTO.TaikhoanDTO;
import javax.swing.ImageIcon;

/**
 *
 * @author PC
 */
public class ThemSPGUI extends javax.swing.JFrame {

    /**
     * Creates new form SanPham_Add
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    
    TaikhoanBUS taikhoanBUS;
    TaikhoanDTO taikhoan;
    
    public ThemSPGUI(String username) throws Exception {
        initComponents();
        taikhoanBUS = new TaikhoanBUS();
        taikhoan = taikhoanBUS.getTaiKhoanByMaTK(username);
        
        SanphamBUS bus = new SanphamBUS();
        
        String KeyString = bus.taoMaSP();
        
        txt_MaSP.setText(KeyString);
        txt_SoLuong.setText("1");
        txt_TenSP.requestFocus();
    }

    public void setTxt_MaLoai(String txt) {
        txt_MaLoai.setText(txt);
    }

    public void setTxt_MaNSX(String txt) {
        txt_MaNSX.setText(txt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_MaSP = new javax.swing.JTextField();
        txt_TenSP = new javax.swing.JTextField();
        txt_SoLuong = new javax.swing.JTextField();
        txt_DonGia = new javax.swing.JTextField();
        txt_MaLoai = new javax.swing.JTextField();
        txt_MaNSX = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnTimLoai = new javax.swing.JButton();
        btnTimNSX = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnTrolai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txt_MaSP.setEditable(false);
        txt_MaSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MaSPKeyPressed(evt);
            }
        });

        txt_TenSP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_TenSPKeyPressed(evt);
            }
        });

        txt_SoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_SoLuongKeyPressed(evt);
            }
        });

        txt_DonGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_DonGiaKeyPressed(evt);
            }
        });

        txt_MaLoai.setEditable(false);
        txt_MaLoai.setText("Chọn Mã Loại Sản Phẩm");
        txt_MaLoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MaLoaiKeyPressed(evt);
            }
        });

        txt_MaNSX.setEditable(false);
        txt_MaNSX.setText("Chọn Mã Nhà Sản Xuất");
        txt_MaNSX.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MaNSXKeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("000 Blambot Casual [TeddyBear]", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thêm Sản Phẩm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ImageIcon icon = new ImageIcon("src\\img\\icon\\icon thêm.png");
        jLabel1.setIcon(icon);
        btnThem.setIcon(icon);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Mã Sản Phẩm :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Nhà Sản Xuất :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Tên Sản Phẩm :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Số Lượng :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Đơn Giá :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Loại Sản Phẩm :");

        btnTimLoai.setText("...");
        btnTimLoai.setFocusPainted(false);
        btnTimLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimLoaiActionPerformed(evt);
            }
        });

        btnTimNSX.setText("...");
        btnTimNSX.setFocusPainted(false);
        btnTimNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimNSXActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TenSP, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_SoLuong, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_DonGia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_MaSP)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_MaNSX, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(txt_MaLoai))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTimLoai, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTimNSX, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_TenSP)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_SoLuong)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_DonGia)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txt_MaLoai)
                    .addComponent(btnTimLoai, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(txt_MaNSX)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTimNSX)))
                .addContainerGap())
        );

        btnThem.setBackground(new java.awt.Color(204, 255, 153));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnTrolai.setText("Trở Lại");
        btnTrolai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrolaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(67, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTrolai, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTrolai))
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        SanphamBUS bus = new SanphamBUS();
        SanPhamDTO sp = new SanPhamDTO();
        initDefaultBUS initChooseID = new initDefaultBUS();
        
        txt_TenSP.setText(txt_TenSP.getText().trim());
        
        if("".equals(txt_TenSP.getText().trim())){
            JOptionPane.showMessageDialog(this,"Tên sản phẩm không được rỗng!");
            txt_TenSP.requestFocus();
        }
        else
            try {
                if(!bus.validName(txt_TenSP.getText())){
                    JOptionPane.showMessageDialog(this, "Tên sản phẩm đã tồn tại!");
                    txt_TenSP.requestFocus();
                }
                else
                    if("".equals(txt_DonGia.getText().trim())){
                        JOptionPane.showMessageDialog(this,"Đơn giá không được rỗng!");
                        txt_DonGia.requestFocus();
                    }
                    else
                        if(txt_SoLuong.getText().trim().equals("")){
                            JOptionPane.showMessageDialog(this, "Số lượng không được rỗng!");
                            txt_SoLuong.requestFocus();
                        }
                        else
                        if(!bus.validNumber(txt_SoLuong.getText())){
                            JOptionPane.showMessageDialog(this,"Số lượng sản phẩm không được chứa chữ cái và phải là số dương!");
                            txt_SoLuong.requestFocus();
                        }
                        else
                            if(!bus.validNumber(txt_DonGia.getText())){
                                JOptionPane.showMessageDialog(this,"Đơn giá sản phẩm không được chứa chữ cái và phải là số dương!");
                                txt_DonGia.requestFocus();
                            }
                            else
                                try {
                                    if(txt_MaNSX.getText().equals(initChooseID.getTxtMaNSX())){
                                        JOptionPane.showMessageDialog(this, "Vui lòng chọn Mã Nhà Sản Xuất!");
                                    }
                                    else
                                        if(txt_MaLoai.getText().equals(initChooseID.getTxtMaLoaiSP())){
                                            JOptionPane.showMessageDialog(this, "Vui lòng chọn Mã Loại Sản Phẩm!");
                                        }
                                        else
                                        {
                                            sp.setTenSP(txt_TenSP.getText());
                                            sp.setMaSP(txt_MaSP.getText());
                                            sp.setDonGia(parseFloat(txt_DonGia.getText()));
                                            sp.setSoLuong(parseInt(txt_SoLuong.getText()));
                                            sp.setMaNSX(txt_MaNSX.getText());
                                            sp.setMaLoai(txt_MaLoai.getText());
                                            
                                            txt_TenSP.setText("");
                                            txt_SoLuong.setText("1");
                                            txt_DonGia.setText("");
                                            try {
                                                txt_MaNSX.setText(initChooseID.getTxtMaNSX());
                                                txt_MaLoai.setText(initChooseID.getTxtMaLoaiSP());
                                            } catch (Exception ex) {
                                                Logger.getLogger(ThemSPGUI.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                            
                                            try {
                                                bus.them(sp);
                                            } catch (Exception ex) {
                                                Logger.getLogger(ThemSPGUI.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                            
                                            String KeyString = "";
                                            
                                            try {
                                                KeyString = bus.taoMaSP();
                                            } catch (Exception ex) {
                                                Logger.getLogger(ThemSPGUI.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                            
                                            txt_MaSP.setText(KeyString);
                                            txt_TenSP.requestFocus();
                                        }
                                } catch (Exception ex) {
                                    Logger.getLogger(ThemSPGUI.class.getName()).log(Level.SEVERE, null, ex);
                                }
        } catch (Exception ex) {
            Logger.getLogger(ThemSPGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void txt_MaSPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MaSPKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        txt_TenSP.requestFocus();
    }//GEN-LAST:event_txt_MaSPKeyPressed

    private void txt_TenSPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_TenSPKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        txt_SoLuong.requestFocus();
        else
        if(evt.getKeyCode() == KeyEvent.VK_UP)
        txt_MaSP.requestFocus();
    }//GEN-LAST:event_txt_TenSPKeyPressed

    private void txt_SoLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_SoLuongKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        txt_DonGia.requestFocus();
        else
        if(evt.getKeyCode() == KeyEvent.VK_UP)
        txt_TenSP.requestFocus();
    }//GEN-LAST:event_txt_SoLuongKeyPressed

    private void txt_DonGiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DonGiaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        txt_MaLoai.requestFocus();
        else
        if(evt.getKeyCode() == KeyEvent.VK_UP)
        txt_SoLuong.requestFocus();
    }//GEN-LAST:event_txt_DonGiaKeyPressed

    private void txt_MaLoaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MaLoaiKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        txt_MaNSX.requestFocus();
        else
        if(evt.getKeyCode() == KeyEvent.VK_UP)
        txt_DonGia.requestFocus();     
    }//GEN-LAST:event_txt_MaLoaiKeyPressed

    private void txt_MaNSXKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MaNSXKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP)
        txt_MaLoai.requestFocus();       
    }//GEN-LAST:event_txt_MaNSXKeyPressed

    private void btnTrolaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrolaiActionPerformed
        try {
            new SanPhamGUI(taikhoan.getMaTK()).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(ThemSPGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();                
    }//GEN-LAST:event_btnTrolaiActionPerformed

    private void btnTimNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimNSXActionPerformed
        try {
            new SearchNSX(this).setVisible(true);        // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(ThemSPGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimNSXActionPerformed

    private void btnTimLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimLoaiActionPerformed
        try {
            new SearchLoaiSP(this).setVisible(true);        // TODO add your handling code here:
        } catch (Exception ex) {
            Logger.getLogger(ThemSPGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTimLoaiActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ThemSPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ThemSPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ThemSPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ThemSPGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new ThemSPGUI().setVisible(true);
//                } catch (Exception ex) {
//                    Logger.getLogger(ThemSPGUI.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimLoai;
    private javax.swing.JButton btnTimNSX;
    private javax.swing.JButton btnTrolai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt_DonGia;
    public javax.swing.JTextField txt_MaLoai;
    public javax.swing.JTextField txt_MaNSX;
    private javax.swing.JTextField txt_MaSP;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_TenSP;
    // End of variables declaration//GEN-END:variables
}
